"use client";

import { useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowLeft, Megaphone, Instagram, Twitter, Calendar, Check, X, Image as ImageIcon, Sparkles } from 'lucide-react';
import { Card } from '../../components/ui/Card';
import styles from '../clients/page.module.css';

const mockPosts = [
  {
    id: 1,
    platform: 'Instagram',
    status: 'pending_approval',
    date: 'Mañana, 18:00',
    reason: 'El fin de semana hará sol (25ºC) y tenemos 4 habitaciones libres. Estrategia: Last-Minute Getaway.',
    image: 'https://images.unsplash.com/photo-1542314831-c6a4d27ece50?w=500&q=80',
    copy: '☀️ ¡El fin de semana promete sol radiante! Escápate a la tranquilidad. Tenemos las últimas 4 habitaciones disponibles. Reserva con el código SUNNY25 y llévate desayuno gratis. 🌴✨ #Escapada #LastMinute',
  },
  {
    id: 2,
    platform: 'Twitter',
    status: 'published',
    date: 'Hoy, 10:00',
    reason: 'Responder a tendencia local #GastronomiaMadrid.',
    copy: '¿Sabías que nuestro restaurante ahora utiliza productos 100% km0 de huertos locales? Apoyando la economía circular. 🍅🥬 #GastronomiaMadrid',
  }
];

export default function SocialLobePage() {
  const [posts, setPosts] = useState(mockPosts);

  const handleApprove = (id: number) => {
    setPosts(prev => prev.map(p => p.id === id ? { ...p, status: 'scheduled' } : p));
  };

  return (
    <div className={styles.container}>
      <header className={styles.header} style={{ marginBottom: '2rem' }}>
        <div>
          <Link href="/"
            style={{
              color: 'var(--text-muted)',
              marginBottom: '1rem',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.5rem',
              fontSize: '0.9rem',
              textDecoration: 'none',
              transition: 'color 0.2s'
            }}
          >
            <ArrowLeft size={16} /> Volver al Dashboard
          </Link>
          <motion.h1 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            style={{ fontSize: '2rem', fontWeight: 600, margin: '0 0 0.5rem 0', color: 'var(--foreground)', display: 'flex', alignItems: 'center', gap: '0.75rem' }}
          >
            <Megaphone size={28} color="var(--primary)" /> Lóbulo de Marketing (Community Manager)
          </motion.h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '1.1rem' }}>El AGI analiza inventario, clima y tendencias para generar campañas de marketing autónomas.</p>
        </div>
      </header>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(12, 1fr)', gap: '2rem' }}>
        {/* Left Column: Feed */}
        <div style={{ gridColumn: 'span 8', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 600, margin: 0, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Sparkles size={20} color="var(--primary)"/> Propuestas del Agente
          </h2>
          
          {posts.map((post, i) => (
            <motion.div key={post.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }}>
              <Card style={{ padding: 0, overflow: 'hidden', border: post.status === 'pending_approval' ? '1px solid var(--primary)' : '1px solid var(--border-subtle)' }}>
                <div style={{ padding: '1rem 1.5rem', background: 'rgba(255,255,255,0.03)', borderBottom: '1px solid var(--border-subtle)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    {post.platform === 'Instagram' ? <Instagram size={20} color="#E1306C"/> : <Twitter size={20} color="#1DA1F2"/>}
                    <div style={{ fontWeight: 600 }}>{post.platform}</div>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                    <Calendar size={14} /> {post.date}
                  </div>
                </div>
                
                <div style={{ padding: '1.5rem', display: 'flex', gap: '1.5rem' }}>
                  {post.image && (
                    <div style={{ width: '200px', height: '200px', borderRadius: '12px', overflow: 'hidden', flexShrink: 0, position: 'relative' }}>
                      <img src={post.image} alt="Generated by AI" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                      <div style={{ position: 'absolute', top: '0.5rem', left: '0.5rem', background: 'rgba(0,0,0,0.6)', padding: '0.2rem 0.5rem', borderRadius: '4px', fontSize: '0.6rem', color: 'white', display: 'flex', gap: '0.25rem', alignItems: 'center' }}>
                        <ImageIcon size={10}/> IA GENERADA
                      </div>
                    </div>
                  )}
                  <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
                    <div>
                      <div style={{ fontSize: '0.8rem', color: 'var(--primary)', textTransform: 'uppercase', fontWeight: 700, marginBottom: '0.5rem' }}>
                        Lógica del Agente:
                      </div>
                      <p style={{ margin: '0 0 1rem 0', fontSize: '0.95rem', color: 'var(--text-muted)', fontStyle: 'italic', borderLeft: '2px solid var(--primary)', paddingLeft: '1rem' }}>
                        {post.reason}
                      </p>
                      <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 700, marginBottom: '0.5rem' }}>
                        Copy Propuesto:
                      </div>
                      <p style={{ margin: 0, fontSize: '1.05rem', lineHeight: 1.5, color: 'var(--foreground)' }}>
                        {post.copy}
                      </p>
                    </div>

                    {post.status === 'pending_approval' && (
                      <div style={{ display: 'flex', gap: '1rem', marginTop: '1.5rem' }}>
                        <button 
                          onClick={() => handleApprove(post.id)}
                          style={{ flex: 1, padding: '0.75rem', background: 'var(--success)', color: 'white', border: 'none', borderRadius: '8px', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', cursor: 'pointer' }}
                        >
                          <Check size={18} /> Aprobar y Agendar
                        </button>
                        <button style={{ flex: 1, padding: '0.75rem', background: 'transparent', color: 'var(--danger)', border: '1px solid var(--danger)', borderRadius: '8px', fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', cursor: 'pointer' }}>
                          <X size={18} /> Rechazar
                        </button>
                      </div>
                    )}
                    {post.status === 'scheduled' && (
                      <div style={{ marginTop: '1.5rem', padding: '0.75rem', background: 'rgba(16, 185, 129, 0.1)', color: 'var(--success)', borderRadius: '8px', textAlign: 'center', fontWeight: 600 }}>
                        ✅ Agendado correctamente
                      </div>
                    )}
                    {post.status === 'published' && (
                      <div style={{ marginTop: '1.5rem', padding: '0.75rem', background: 'rgba(255,255,255,0.05)', color: 'var(--text-muted)', borderRadius: '8px', textAlign: 'center', fontWeight: 600 }}>
                        📢 Publicado
                      </div>
                    )}
                  </div>
                </div>
              </Card>
            </motion.div>
          ))}
        </div>

        {/* Right Column: Stats */}
        <div style={{ gridColumn: 'span 4', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
           <Card style={{ padding: '1.5rem', background: 'var(--surface-dark)' }}>
              <h3 style={{ margin: '0 0 1rem 0', fontSize: '1.1rem', color: 'var(--foreground)' }}>Estadísticas AGI</h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Posts Generados (Mes)</span>
                  <span style={{ fontSize: '1.2rem', fontWeight: 600 }}>42</span>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Tasa de Aprobación</span>
                  <span style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--success)' }}>94%</span>
                </div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>Conversiones Estimadas</span>
                  <span style={{ fontSize: '1.2rem', fontWeight: 600, color: 'var(--primary)' }}>+15%</span>
                </div>
              </div>
           </Card>
        </div>

      </div>
    </div>
  );
}
